### ISSUE TITLE
KeyError: 'message'

### ISSUE THREAD

**Issue by eanunez** [GearPlug/surveymonkey-python#5]
Hi, 

I encountered this problem. 
Traceback (most recent call last):
  File "C:/Users/emman/PycharmProjects/surveymonkey_api/get_survey.py", line 168, in <module>
    sm = SurveyMonkey()
  File "C:/Users/emman/PycharmProjects/surveymonkey_api/get_survey.py", line 61, in transform_data
    page_id=page_id, question_id=question_id)
  File "C:\Users\emman\PycharmProjects\surveymonkey_api\lib\site-packages\surveymonkey\client.py", line 452, in get_specific_question
    return self._get(url)
  File "C:\Users\emman\PycharmProjects\surveymonkey_api\lib\site-packages\surveymonkey\client.py", line 708, in _get
    return self._request('GET', endpoint, **kwargs)
  File "C:\Users\emman\PycharmProjects\surveymonkey_api\lib\site-packages\surveymonkey\client.py", line 724, in _request
    return self._parse(requests.request(method, url, headers=_headers, **kwargs))
  File "C:\Users\emman\PycharmProjects\surveymonkey_api\lib\site-packages\surveymonkey\client.py", line 733, in _parse
    self.get_error(dict(r))
  File "C:\Users\emman\PycharmProjects\surveymonkey_api\lib\site-packages\surveymonkey\client.py", line 747, in get_error
    error_message = error['message']
KeyError: 'message'

Whenever there is an Error in requests, it always show the same message. I would like to know about the request error info but I think the error is not handled properly so it is showing this keyerror message.

**Comment by eanunez** [comment]
I solved the problem. The error message is contained in the a dict of dict. So, I modified the following lines at client.py
Line 747: `error_message` = `error['error']['message']`
Line 795: `raise UnknownError("UNKNOWN ERROR: {}".format(error['error']['message']))`
